"""Generated by rowstile client from the policy. Do not edit; re-run after changing the policy.

Works with any DB-API connection using %s placeholders (psycopg, psycopg2):

    with conn.transaction():                     # psycopg 3; or: BEGIN ... COMMIT
        Authz(conn).sign_in(7)                   # SELECT authz.act_as('user', '7')
        if Authz(conn).can("file", 11, "edit"): ...
"""
from __future__ import annotations

import datetime
import json
import uuid
from collections.abc import Sequence
from types import TracebackType
from typing import TYPE_CHECKING, Literal, Protocol, TypeVar

if TYPE_CHECKING:
    from typing import LiteralString  # Python 3.11

PERMISSIONS: dict[str, list[str]] = {
    "document": [
        "share",
        "edit",
        "view"
    ]
}
SHARED_RELATIONS: dict[str, dict[str, list[str]]] = {
    "document": {
        "editor": [
            "user",
            "team#member"
        ],
        "viewer": [
            "user",
            "team#member"
        ]
    }
}
SCOPES: list[str] = []

ObjectType = Literal["document"]
Permission = Literal["edit", "share", "view"]
DocumentPermission = Literal["share", "edit", "view"]
# an object's id; for a composite key, its columns in order: (org_id, id)
Id = int | str | uuid.UUID | tuple[int | str | uuid.UUID, ...]
When = datetime.datetime | str                  # a timestamptz: a datetime, or text Postgres reads
Row = dict[str, object]
Result = TypeVar("Result")


class Cursor(Protocol):
    """What the client uses of a DB-API cursor (psycopg's, psycopg2's)."""
    @property
    def description(self) -> Sequence[Sequence[object]] | None: ...
    def execute(self, query: LiteralString, params: Sequence[object], /) -> object: ...
    def fetchone(self) -> Sequence[object] | None: ...
    def fetchall(self) -> Sequence[Sequence[object]]: ...
    def __enter__(self) -> Cursor: ...
    def __exit__(self, exc_type: type[BaseException] | None, exc: BaseException | None,
                 tb: TracebackType | None, /) -> object: ...


class Connection(Protocol):
    def cursor(self) -> Cursor: ...


def _texts(value: object) -> list[str]:
    """A text[] from the database (None: none)."""
    return [str(x) for x in value] if isinstance(value, (list, tuple)) else []


def _int(value: object) -> int:
    if isinstance(value, (int, str)):
        return int(value)
    raise TypeError(f"expected a number from the database, got {value!r}")


def _id(x: Id) -> str:
    """A composite key as Postgres writes a row: every field quoted, quotes and backslashes escaped."""
    if isinstance(x, (tuple, list)):
        return "(" + ",".join('"' + str(v).replace("\\", "\\\\").replace('"', '\\"') + '"' for v in x) + ")"
    return str(x)


class Refused(Exception):
    """The database refused a write (SQLSTATE 42501): its message, the table and command, and why (lines)."""

    def __init__(self, message: str, table: str | None = None, command: str | None = None, why: Sequence[str] = ()) -> None:
        super().__init__(message)
        self.message, self.table, self.command, self.why = message, table, command, list(why)


class NotFound(Exception):
    """The row isn't there, or the signed-in user can't see it."""

    def __init__(self, table: str, id_: str) -> None:
        super().__init__(f"{table} {id_} not found")
        self.table, self.id = table, id_


def refusal(error: BaseException) -> Refused | None:
    """A Refused for a database error that is a refusal, else None (psycopg, psycopg2)."""
    if (getattr(error, "sqlstate", None) or getattr(error, "pgcode", None)) != "42501":
        return None
    diag = getattr(error, "diag", None)
    message = getattr(diag, "message_primary", None) or str(error).split("\n")[0]
    detail = getattr(diag, "message_detail", None) or ""
    schema, table = getattr(diag, "schema_name", None), getattr(diag, "table_name", None)
    constraint = getattr(diag, "constraint_name", None) or ""
    return Refused(message, f"{schema}.{table}" if schema and table else table,
                   constraint[6:] if constraint.startswith("authz_") else None, detail.split("\n") if detail else [])


class Authz:
    def __init__(self, conn: Connection) -> None:
        self.conn = conn

    def _one(self, sql: LiteralString, args: Sequence[object]) -> object:
        with self.conn.cursor() as cur:
            cur.execute(sql, args)
            row = cur.fetchone()
            return row[0] if row else None

    def _all(self, sql: LiteralString, args: Sequence[object]) -> Sequence[str]:
        with self.conn.cursor() as cur:
            cur.execute(sql, args)
            return [str(r[0]) for r in cur.fetchall()]

    def _rows(self, sql: LiteralString, args: Sequence[object]) -> Sequence[Row]:
        with self.conn.cursor() as cur:
            cur.execute(sql, args)
            names = [str(d[0]) for d in cur.description or []]
            return [dict(zip(names, r, strict=True)) for r in cur.fetchall()]

    @staticmethod
    def _check(type_: str, perm: str) -> None:
        if type_ not in PERMISSIONS or perm not in PERMISSIONS[type_]:
            raise ValueError(f"{type_} has no permission {perm!r} in the policy")

    def sign_in(self, user_id: Id | None) -> None:
        """For this transaction only (run inside a transaction); None: nobody. A signed session (authz.act_as)."""
        self._one("SELECT authz.act_as('user', %s)", (None if user_id is None else _id(user_id),))

    def sign_in_as(self, principal_type: str, principal_id: Id) -> None:
        """A principal other than a user (a service), for this transaction only."""
        self._one("SELECT authz.act_as(%s, %s)", (principal_type, _id(principal_id)))

    def connection_check(self) -> Sequence[Row]:
        """What is wrong with this connection, as rows of severity and problem: call it when the app starts, and
        refuse to start on an 'error' (a role row-level security doesn't apply to, or one the policy doesn't govern)."""
        return self._rows("SELECT severity, problem FROM authz.connection_check()", ())

    def principal(self) -> tuple[str, str] | None:
        """(type, id) of whoever is signed in, or None."""
        rows = self._all("SELECT principal_type || ':' || principal_id FROM authz.principal()", ())
        if not rows:
            return None
        kind, _, pid = rows[0].partition(":")
        return kind, pid

    def login_key(self, key: str) -> None:
        self._one("SELECT authz.login_key(%s)", (key,))

    def login_jwt(self, token: str) -> None:
        self._one("SELECT authz.login_jwt(%s)", (token,))

    def create_api_key(self, name: str, scopes: str = "", expires_at: When | None = None, principal_type: str | None = None,
                       principal_id: Id | None = None) -> str:
        """A key for yourself, or (holding manage_keys on it) for a principal such as a service. Shown once."""
        return str(self._one("SELECT authz.create_api_key(%s, %s, %s, %s, %s)",
                             (name, scopes, expires_at, principal_type, None if principal_id is None else _id(principal_id))))

    def list_api_keys(self, principal_type: str | None = None, principal_id: Id | None = None) -> Sequence[Row]:
        return self._rows("SELECT * FROM authz.list_api_keys(%s, %s)",
                          (principal_type, None if principal_id is None else _id(principal_id)))

    def revoke_api_key(self, key_id: int) -> None:
        self._one("SELECT authz.revoke_api_key(%s)", (key_id,))

    def can(self, type_: ObjectType, id_: Id, perm: Permission) -> bool:
        self._check(type_, perm)
        return bool(self._one("SELECT authz.can(%s, %s::text, %s)", (type_, _id(id_), perm)))

    def list(self, type_: ObjectType, perm: Permission, after: Id | None = None,
             limit: int | None = None) -> Sequence[str]:
        """Every id the user holds perm on; with limit, a page in key order after `after`."""
        self._check(type_, perm)
        return self._all("SELECT x FROM authz.list(%s, %s, %s, %s) x",
                         (type_, perm, None if after is None else _id(after), limit))

    def perms(self, type_: ObjectType, id_: Id) -> Sequence[str]:
        return _texts(self._one("SELECT authz.perms(%s, %s::text)", (type_, _id(id_))))

    def who(self, type_: ObjectType, id_: Id, perm: Permission) -> Sequence[str]:
        self._check(type_, perm)
        return self._all("SELECT x FROM authz.who(%s, %s::text, %s) x", (type_, _id(id_), perm))

    def explain(self, type_: ObjectType, id_: Id, perm: Permission, user: Id | None = None) -> Sequence[str]:
        return self._all("SELECT e FROM authz.explain(%s, %s::text, %s, %s) e",
                         (type_, _id(id_), perm, None if user is None else _id(user)))

    def share(self, type_: str, id_: Id, relation: str, subject_type: str, subject_id: Id, subject_relation: str = "",
              expires_at: When | None = None, starts_at: When | None = None, caveat: str | None = None,
              caveat_args: str | None = None) -> None:
        if relation not in SHARED_RELATIONS.get(type_, {}):
            raise ValueError(f"{type_}.{relation} is not shared in the policy")
        self._one("SELECT authz.share(%s, %s::text, %s, %s, %s::text, %s, %s, %s, %s, %s::jsonb)",
                  (type_, _id(id_), relation, subject_type, _id(subject_id), subject_relation, expires_at, starts_at,
                   caveat, caveat_args))

    def create_link(self, type_: str, id_: Id, relation: str, expires_at: When | None = None) -> str:
        """A share with anyone holding the returned token (shown once; only its hash is stored)."""
        if relation not in SHARED_RELATIONS.get(type_, {}):
            raise ValueError(f"{type_}.{relation} is not shared in the policy")
        return str(self._one("SELECT authz.create_link(%s, %s::text, %s, %s)", (type_, _id(id_), relation, expires_at)))

    def list_links(self, type_: ObjectType, id_: Id) -> Sequence[Row]:
        """The links on an object (id, relation, created_by, created_at, expires_at), for those who can share it
        or may make such links."""
        return self._rows("SELECT * FROM authz.list_links(%s, %s::text)", (type_, _id(id_)))

    def revoke_link(self, type_: ObjectType, id_: Id, link_id: str) -> None:
        """Turns a link off, by its id in list_links (not its token)."""
        self._one("SELECT authz.revoke_link(%s, %s::text, %s)", (type_, _id(id_), link_id))

    def use_links(self, tokens: Sequence[str]) -> None:
        """Link tokens the request presents, for this transaction (SET LOCAL authz_ctx.links)."""
        self._one("SELECT set_config('authz_ctx.links', %s, true)", (",".join(tokens),))

    def unshare(self, type_: str, id_: Id, relation: str, subject_type: str, subject_id: Id, subject_relation: str = "") -> None:
        self._one("SELECT authz.unshare(%s, %s::text, %s, %s, %s::text, %s)",
                  (type_, _id(id_), relation, subject_type, _id(subject_id), subject_relation))

    def request_access(self, type_: str, id_: Id, relation: str, reason: str, duration: str | None = None) -> int:
        return _int(self._one("SELECT authz.request_access(%s, %s::text, %s, %s, %s::interval)",
                              (type_, _id(id_), relation, reason, duration)))

    def decide_request(self, request_id: int, approve: bool, note: str | None = None) -> None:
        self._one("SELECT authz.decide_request(%s, %s, %s)", (request_id, approve, note))

    def cancel_request(self, request_id: int) -> None:
        self._one("SELECT authz.cancel_request(%s)", (request_id,))

    def pending_requests(self) -> Sequence[Row]:
        """Requests the user may decide, and their own (mine = true)."""
        return self._rows("SELECT * FROM authz.pending_requests()", ())

    def list_shares(self, type_: ObjectType, id_: Id) -> Sequence[Row]:
        """The shares on an object, for a sharing dialog."""
        return self._rows("SELECT * FROM authz.list_shares(%s, %s::text)", (type_, _id(id_)))

    def break_glass(self, type_: str, id_: Id, relation: str, reason: str, duration: str = "1 hour") -> None:
        self._one("SELECT authz.break_glass(%s, %s::text, %s, %s, %s::interval)", (type_, _id(id_), relation, reason, duration))

    def start_review(self, type_: ObjectType, id_: Id, closes_at: When | None = None) -> int:
        return _int(self._one("SELECT authz.start_review(%s, %s::text, coalesce(%s::timestamptz, now() + interval '14 days'))",
                              (type_, _id(id_), closes_at)))

    def review_items(self, review_id: int) -> Sequence[Row]:
        return self._rows("SELECT * FROM authz.review_items(%s)", (review_id,))

    def review_decide(self, review_id: int, item: int, keep: bool) -> None:
        self._one("SELECT authz.review_decide(%s, %s, %s)", (review_id, item, keep))

    def close_review(self, review_id: int, revoke_undecided: bool = False) -> int:
        return _int(self._one("SELECT authz.close_review(%s, %s)", (review_id, revoke_undecided)))

    def explain_rule(self, table: str, command: str, id_: Id | None = None, row: Row | None = None) -> Sequence[str] | None:
        """Why a write is or would be refused: an insert (row: the new row), or an update or delete of the row with
        this id (for an update, row: the new values). None: that row isn't there, or you can't see it."""
        lines = self._one("SELECT authz.explain_rule(%s, %s, %s, %s::jsonb)",
                          (table, command, None if id_ is None else _id(id_),
                           None if row is None else json.dumps(row, default=str)))
        return None if lines is None else _texts(lines)

    def expect(self, result: Result, table: str, command: str, id_: Id, row: Row | None = None) -> Result:
        """The result of an UPDATE or DELETE (a row, rows, a count, or the cursor that ran it: its rowcount):
        returned if anything changed, otherwise NotFound (you can't see the row, or the rule allows the write and
        the statement matched nothing for another reason) or Refused (you may not, and why)."""
        count = getattr(result, "rowcount", None)
        if count > 0 if isinstance(count, int) and not isinstance(count, bool) else bool(result):
            return result
        why = self.explain_rule(table, command, id_, row)
        if why is None or (why and why[0].lstrip().startswith("yes")):
            raise NotFound(table, _id(id_))
        raise Refused(f"permission denied: may not {command} {table} {_id(id_)}", table, command, why)

    @staticmethod
    def refusal(error: BaseException) -> Refused | None:
        return refusal(error)

    def who_among(self, type_: ObjectType, id_: Id, perm: Permission, principals: Sequence[Id],
                  principal_type: str = "user") -> Sequence[str]:
        """Which of these people (or principals of another type) hold perm: one call, for live updates. Signs each
        one in, so it needs what signing in needs (SET on authz.user_id)."""
        self._check(type_, perm)
        return self._all("SELECT x FROM authz.who_among(%s, %s::text, %s, %s::text[], %s) x",
                         (type_, _id(id_), perm, [_id(p) for p in principals], principal_type))
