"""rowstile: authz policy

Revision ID: 7744a41c9038
Revises: 201910824bab
Create Date: 2026-10-07 11:44:01

Generated by rowstile migrate from the policy: the SQL is in 7744a41c9038_authz_policy.sql, beside this file. Don't edit
either; change the policy and run rowstile migrate again.
"""
from pathlib import Path

from alembic import op

revision = "7744a41c9038"
down_revision: str | None = '201910824bab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.driver == "asyncpg":
        # asyncpg prepares each statement, and a prepared statement is one command: said here, in a line, rather
        # than by the driver with the whole script in its message
        raise RuntimeError(
            "rowstile: Alembic is connected with asyncpg, which takes one statement at a time, and this revision "
            "is one script. Give Alembic a sync driver (postgresql+psycopg://); the app keeps asyncpg"
        )
    sql = Path(__file__).with_suffix(".sql").read_text(encoding="utf-8")
    # as one script, straight to the driver: the SQL has % signs and colons, which are not parameters
    bind.exec_driver_sql(sql, execution_options={"no_parameters": True})


def downgrade() -> None:
    raise NotImplementedError("a rowstile migration isn't undone: change the policy back and write a new one")
